import {
  Meteor
} from 'meteor/meteor';
import '/imports/collection/processo.js'
import './methods.js'
import './publish.js'
import '/imports/collection/semestre.js'
import '/imports/collection/curso.js'
import '/imports/collection/ofertaDisciplina.js'
import '/imports/collection/voucherCollection.js'
import '/imports/startup/server/captcha.js'
import '/imports/collection/legenda.js'
Meteor.startup(function() {
  var array=[
    {id:'1', pergunta:"Cumprimento do programa da disciplina", resposta:'15'},
    {id:'2', pergunta:"Metodologia didática adotada pelo docente", resposta:'15'},
    {id:'3', pergunta:"Compromisso com o horário da disciplina estabelecido na matrícula", resposta:'15'},
    {id:'4', pergunta:"Segurança e atualização do docente no conteúdo da disciplina", resposta:'15'},
    {id:'5', pergunta:"Atenção do docente fora do horário de aula", resposta:'15'},
    {id:'6', pergunta:"Distribuição entre os conteúdos teóricos e práticos", resposta:'15'},
    {id:'7', pergunta:"Usou critérios claros e adequados na avaliação da aprendizagem", resposta:'15'},
    {id:'8', pergunta:"Cumprimento da carga horária total da disciplina", resposta:'15'},
    {id:'9', pergunta:"Em resumo, avalio a disciplina como sendo", resposta:'15'},
    {id:'10', pergunta:"O curso tem atendido às suas expectativas?", resposta:'sim_nao'},
    {id:'11', pergunta:"Você percebe que há correlação entre as disciplinas do curso?", resposta:'sim_nao'},
    {id:'12', pergunta:"As disciplinas deste semestre, tem exigido trabalhos e pesquisas extraclasse?", resposta:'sim_nao'},
    {id:'13', pergunta:"Você possui algum tipo de bolsa de assistência estudantil?", resposta:'sim_nao'},
    {id:'14', pergunta:"Caso a resposta tenha sido sim para pergunta anterior, qual ou quais bolsas você recebe?", resposta:['permanecia','alimentacao','moradia']},
    {id:'15', pergunta:"Você possui alguma bolsa de extensão, monitoria ou pesquisa?", resposta:'sim_nao'},
    {id:'16', pergunta:"Caso a resposta tenha sido sim para pergunta anterior, quais bolsas você recebe?", resposta:['permanecia','alimentacao','moradia']},
    {id:'17', pergunta:"Realiza estágio?", resposta:'sim_nao'},
    {id:'18', pergunta:"Você frequenta as atividades culturais da UFMT?", resposta:'sim_nao'},
    {id:'19', pergunta:"Você desenvolve atividades esportivas na UFMT?", resposta:'sim_nao'},
    {id:'20', pergunta:"Frequência às aulas", resposta:'15'},
    {id:'21', pergunta:"Participação nas aulas", resposta:'15'},
    {id:'22', pergunta:"Desenvolvimento das atividades propostas pelos professores", resposta:'15'},
    {id:'23', pergunta:"Frequência de consultas ao acervo da Biblioteca Central da UFMT", resposta:'15'},
    {id:'24', pergunta:"Prática de leituras obrigatórias", resposta:'15'},
    {id:'25', pergunta:"Prática de leituras adicionais", resposta:'15'},
    {id:'26', pergunta:"Participação em atividades extracurriculares (seminários, palestras, eventos etc.).", resposta:'15'},
    {id:'27', pergunta:"Interessa por oportunidades de mobilidade acadêmica, participação em eventos e/ou experiências com outras instituições, públicas ou privada", resposta:'15'},
    {id:'28', pergunta:"Fica atento a oportunidades de estágio na área", resposta:'15'},
    {id:'29', pergunta:"Dedicação e empenho junto ao Curso de CURSO da UFMT", resposta:'15'},
    {id:'30', pergunta:"Avalie o comportamento dos demais colegas", resposta:'15'},
    {id:'31', pergunta:"Sua participação em monitoria", resposta:'15'},
    {id:'32', pergunta:"Sua participação em projetos de pesquisa", resposta:'15'},
    {id:'33', pergunta:"Sua participação em projetos de extensão", resposta:'15'},
    {id:'34', pergunta:"Seu desempenho em geral", resposta:'15'},
    {id:'35', pergunta:"Prestativos e acessíveis", resposta:'15'},
    {id:'36', pergunta:"Acesso a informações", resposta:'15'},
    {id:'37', pergunta:"Mostram-se interessados pelo bom desempenho do curso", resposta:'15'},
    {id:'38', pergunta:"Disponibilidade no horário estabelecido", resposta:'15'},
    {id:'39', pergunta:"Prestativos e acessíveis", resposta:'15'},
    {id:'40', pergunta:"Desenvolvimento de projetos de pesquisa", resposta:'15'},
    {id:'41', pergunta:"Desenvolvimento de projetos de extensão", resposta:'15'},
    {id:'42', pergunta:"Orientação", resposta:'15'},
    {id:'43', pergunta:"Secretaria da Coordenação do Curso é acessível", resposta:'15'},
    {id:'44', pergunta:"Coordenador do Curso é acessível", resposta:'15'},
    {id:'45', pergunta:"Secretaria da Direção é acessível", resposta:'15'},
    {id:'46', pergunta:"Diretor da faculdade é acessível", resposta:'15'},
    {id:'47', pergunta:"Secretaria da Pró-reitoria é acessível", resposta:'15'},
    {id:'48', pergunta:"Pró-reitor é acessível", resposta:'15'},
    {id:'49', pergunta:"Auditórios", resposta:'15'},
    {id:'50', pergunta:"Laboratórios", resposta:'15'},
    {id:'51', pergunta:"Aulas de campo e visitas técnicas", resposta:'15'},
    {id:'52', pergunta:"Acervo da biblioteca", resposta:'15'},
    {id:'53', pergunta:"Estrutura da biblioteca", resposta:'15'},
    {id:'54', pergunta:"Restaurante universitário", resposta:'15'},
    {id:'55', pergunta:"Estrutura das salas de aulas", resposta:'15'},
    {id:'56', pergunta:"Espaços de vivência", resposta:'15'},
    {id:'57', pergunta:"Acessibilidade", resposta:'15'},
    {id:'58', pergunta:"Rede de internet", resposta:'15'},
    {id:'59', pergunta:"O que mais precisa melhorar no curso?", resposta:'text'},
    {id:'60', pergunta:"O que mais precisa melhorar na Faculdade de Engenharia?", resposta:'text'},
    {id:'61', pergunta:"O que mais precisa melhorar na UFMT?", resposta:'text'},
    {id:'62', pergunta:"Caso algum item não tenha sido contemplado no formulário, faça um comentário abaixo destacando o tema:", resposta:'text'},
    {id:'63', pergunta:"Número de matrícula:", resposta:'text'},
    {id:'64', pergunta:"Qual o seu gênero?", resposta:['masculino','feminino','nao']},
    {id:'65', pergunta:"Em que ano você nasceu?", resposta:'ano'},
    {id:'66', pergunta:"Qual o seu estado de origem?", resposta:'uf'},
    {id:'67', pergunta:"Qual a cidade de origem?", resposta:'text'},,
    {id:'68', pergunta:"Em que ano você concluiu o ensino médio?", resposta:'ano'},
    {id:'69', pergunta:"CURSO é o curso que você realmente gostaria de fazer?", resposta:'sim_nao'},
    {id:'70', pergunta:"Seu ensino médio foi:", resposta:[{'1':"profissionalizante"},{'2':'regular','3':'supletivo'}, {'4':"tecnico"}]},
    {id:'71', pergunta:"Seu ensino médio foi cursado no período:", resposta:[{'1':"diurno"},{'2':'noturno'},{'3':'integral'}, {'4':"misto(mais de um tipo)"}]},
    {id:'72', pergunta:"Seu ensino médio foi cursado em escola", resposta:[{'1':"Pública estadual"},{'2':'Pública federal ou militar'},{'3':'Privada'}, {'4':"Misto (Mais de um tipo)"},{'5':'Outro'}]},
    {id:'73', pergunta:"Você fez algum cursinho preparatório para o ENEM?",resposta:'sim_nao'},
    {id:'74', pergunta:"Você trabalha?", resposta:[{'1':"Sim, em tempo integral"},{'2':'Sim, meio período'},{'3':'Sim, aos fins de semana'}, {'4':"Sim, esporadicamente"},{'5':'Não trabalho atualmente, mas já trabalhe'},{'6':"Não trabalho atualmente, mas estou buscando emprego"},{'7':'Não'}]},
    {id:'75', pergunta:"Como você se considera?", resposta:[{'1':"Branco"},{'2':'Pardo'},{'3':'Mulato'}, {'4':"Negro"},{'5':'Amarelo'},{'6':"Indígena"},{'7':'Outro'}]},
    {id:'76', pergunta:"Qual o seu estado civil?", resposta:[{'1':"Solteiro"},{'2':'Casado'},{'3':'Outro'}]},
    {id:'77', pergunta:"Quantos vestibulares você já prestou?", resposta:'1_10'},
    {id:'78', pergunta:"Por que motivo você escolheu o curso de CURSO?", resposta:[{'1':"Adequação às aptidões pessoais"},{'2':'Amplas possibilidades salariais'},{'3':'Atuar em área afim'},{'4':'Mercado de trabalho'},{'5':'Prestígio social da profissão'},{'6':'Relação candidato/vaga'},{'7':'Outros'}]},
    {id:'79', pergunta:"Você já concluiu algum curso superior?",resposta:'sim_nao'},
    {id:'80', pergunta:"Se sim, qual?",resposta:'sim_nao'},
    {id:'81', pergunta:"Gostaria de realizar algum comentário com relação ao formulário ou ao curso?",resposta:'text'},
    {id:'82', pergunta:"Número de matrícula",resposta:'text'},
    {id:'83', pergunta:"Em qual ano você concluirá o curso?",resposta:'ano'},
    {id:'84', pergunta:"Em qual semestre você concluirá o curso?",resposta:[{'1':'impar'},{'2':'par'}]},
    {id:'85', pergunta:"Em qual área pretende atuar?", resposta:[{'1':"Abrir negócio próprio"},{'2':'Consultoria'},{'3':'Docência'},{'4':"Servidor público"},{'5':'Funcionário (CLT)'},{'6':'Outra opção'}]},
    {id:'86', pergunta:"Quais modalidades de apoio estudantil você utilizou?", resposta:[{'1':"Auxílio alimentação"},{'2':'Auxílio moradia'},{'3':'Bolsa monitoria'},{'4':"Bolsa permanência"},{'5':'Bolsa PIBIC/PIBIT'},{'6':'Outros'},{'7':'Outros'}]},
    {id:'87', pergunta:"Qual nota você atribui para o corpo docente do curso?", resposta:'15'},
    {id:'88', pergunta:"Qual nota você atribui para a convivência estudantil (colegas, CA, DCE, etc.)?", resposta:'15'},
    {id:'89', pergunta:"Qual nota você atribui para a estrutura curricular?", resposta:'15'},
    {id:'90', pergunta:"Qual nota você atribui para as condições físicas das salas de aula?", resposta:'15'},
    {id:'91', pergunta:"Qual nota você atribui para as condições físicas dos laboratórios?", resposta:'15'},
    {id:'92', pergunta:"Qual nota você atribui para as condições físicas da biblioteca?", resposta:'15'},
    {id:'93', pergunta:"Qual nota você atribui para o atendimento na secretaria do curso?", resposta:'15'},
    {id:'94', pergunta:"Qual nota você atribui para os recursos institucionais (data show, transportes, etc.)?", resposta:'15'},
    {id:'95', pergunta:"Qual nota você atribui aos estágios realizados durante o curso?", resposta:'15'},
    {id:'96', pergunta:"Qual nota você atribui para o seu empenho durante o curso de graduação?", resposta:'15'},
    {id:'97', pergunta:"Qual nota você atribui para o curso de graduação como um todo?", resposta:'15'},
    {id:'98', pergunta:"Gostaria de realizar críticas e sugestões para melhoria do curso?", resposta:'text'},
  ]
  for(x in array){
    var tmp=Legenda.findOne({id:array[x].id})
    if(tmp== null){
      console.log("cadastrar", array[x].id);
      Legenda.insert({
        id:array[x].id,
        pergunta:array[x].pergunta,
        respota:array[x].resposta,
      })
    }
  }
});
